"""empty message

Revision ID: 5495ac805267
Revises: db5bca62d94d
Create Date: 2025-01-30 12:34:33.123623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5495ac805267'
down_revision = 'db5bca62d94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('available', sa.BOOLEAN(), nullable=False),
    sa.Column('number_in_stock', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_books_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_books')
    )
    # ### end Alembic commands ###
