"""empty message

Revision ID: be21395b4ca6
Revises: f2bdc4618545
Create Date: 2025-01-30 12:31:54.173771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be21395b4ca6'
down_revision = 'f2bdc4618545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booklistings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booklistings_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_booklistings_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_booklistings_book_id_books'), 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_booklistings_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_book_listing_id_booklistings', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_seller_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_buyer_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_seller_id_users'), 'users', ['seller_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_buyer_id_users'), 'users', ['buyer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_book_listing_id_booklistings'), 'booklistings', ['book_listing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_book_listing_id_booklistings'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_buyer_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_seller_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_buyer_id_users', 'users', ['buyer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_seller_id_users', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_book_listing_id_booklistings', 'booklistings', ['book_listing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('booklistings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_booklistings_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_booklistings_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_booklistings_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_booklistings_book_id_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
