"""empty message

Revision ID: f2bdc4618545
Revises: 008960985aa0
Create Date: 2025-01-30 12:30:00.395528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bdc4618545'
down_revision = '008960985aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_category_id_categories'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_role', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_role', ['role'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('author')

    op.create_table('_alembic_tmp_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('available', sa.BOOLEAN(), nullable=False),
    sa.Column('number_in_stock', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_books_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_books')
    )
    # ### end Alembic commands ###
